#!/bin/bash

# Leviathan Music Player
# A Web-based music player based on the Leviathan music library manager.
# 
# Copyright (C) 2010-2011 Scott Zeid
# http://me.srwz.us/leviathan/web
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 
# Except as contained in this notice, the name(s) of the above copyright holders
# shall not be used in advertising or otherwise to promote the sale, use or
# other dealings in this Software without prior written authorization.

if [ ! -w "/etc/shadow" ]; then
 echo "WARNING:  It is recommended that you run this script as root."
fi

cd "$(dirname "$0")"

OLD_DEBS=""
[ -f "config" ] && . ./config

PREFIX=$1

# Clean up old deb files if $OLD_DEBS is set
if [ "$OLD_DEBS" = "/dev/null" ]; then
 rm ./*.deb
elif [ ! "$OLD_DEBS" = "" -a -d "$OLD_DEBS" ]; then
 mv ./*.deb "$OLD_DEBS" &>/dev/null
fi

# Temporary directory for .deb building
mkdir debtmp &>/dev/null
cd debtmp
rm ./*.deb &>/dev/null

# Copying
mkdir -p files/usr/bin
mkdir -p files/usr/share/applications
mkdir -p files/usr/share/icons/hicolor/16x16/apps
mkdir -p files/usr/share/icons/hicolor/22x22/apps
mkdir -p files/usr/share/icons/hicolor/24x24/apps
mkdir -p files/usr/share/icons/hicolor/32x32/apps
mkdir -p files/usr/share/icons/hicolor/48x48/apps
mkdir -p files/usr/share/icons/hicolor/scalable/apps
mkdir -p files/DEBIAN
cp -a ../../icon .
cp -a ../DEBIAN/* files/DEBIAN/
cp -a ../webleviathan-gtk.py files/usr/bin/webleviathan-gtk
cp -a ../webleviathan-gtk.desktop files/usr/share/applications/
cp -a ../icon/16.png files/usr/share/icons/hicolor/16x16/apps/webleviathan-gtk.png
cp -a ../icon/22.png files/usr/share/icons/hicolor/22x22/apps/webleviathan-gtk.png
cp -a ../icon/24.png files/usr/share/icons/hicolor/24x24/apps/webleviathan-gtk.png
cp -a ../icon/32.png files/usr/share/icons/hicolor/32x32/apps/webleviathan-gtk.png
cp -a ../icon/48.png files/usr/share/icons/hicolor/48x48/apps/webleviathan-gtk.png
cp -a ../icon/scalable.svg files/usr/share/icons/hicolor/scalable/apps/webleviathan-gtk.svg
chmod +x files/usr/bin/webleviathan-gtk

# Change permissions of the files if root
if [ -w "/etc/shadow" ]; then
 chown -R root:root files
fi

# Build .deb and move it
dpkg-deb -b files .
DEBFILE=`ls | grep .deb`
mv $DEBFILE ../$PREFIX$DEBFILE
cd ..

# Change owner of the package if using sudo
if [ -n "$SUDO_UID" -a -n "$SUDO_GID" ]; then
 chown $SUDO_UID:$SUDO_GID $PREFIX$DEBFILE
fi

# Clean up
rm -r debtmp
